//
//  AirwindowsBridge.mm
//  AirwindowsDSP framework
//
//  Two distinct surfaces share this file:
//
//  1. AirwindowsEffectInfo + AirwindowsEngine CLASS METHODS
//     --------------------------------------------------------------
//     Metadata + browsing surface for the UI. Walks Chris's
//     AirwinRegistry (350+ effects) and exposes effect names, categories,
//     parameter counts, mono/stereo flags, first-commit dates, and
//     blog-post / video links to Swift.
//
//     Two override layers sit on top of upstream data:
//
//       category_overrides.json   Reassigns "Unclassified" or
//                                 wrong-bucketed effects to better
//                                 categories. Loaded from the framework
//                                 bundle. Underscore-prefixed keys
//                                 (_comment, etc.) are skipped so the
//                                 JSON can carry human notes.
//
//       effect_links.json         Per-effect blog post + YouTube URLs,
//                                 used by the chip row in
//                                 EffectDetailView.
//
//     The override layer exists because upstream files (ModuleAdd.h,
//     awpdoc descriptions) are regenerated whenever the airwin2rack DSP
//     is synced. Direct edits there would be lost; JSON sidecars in
//     AirwindowsDSP/Resources/ survive.
//
//  2. AirwindowsEngine INSTANCES
//     --------------------------------------------------------------
//     A non-realtime, single-effect processor used by the standalone
//     host-shell app (AirwindowsApp) to preview audio. The AUv3 path is
//     a different class — AirwindowsAudioUnit — with its own processor
//     and threading model. They do not share state.
//
//  RELATED FILES
//  -------------
//    AirwindowsBridge.h          Public ObjC interface, called from Swift.
//    AirwindowsAudioUnit.mm      The AUv3 audio engine (separate path).
//    ../Resources/*.json         Where the override JSONs live.
//    EffectBrowseModel.swift     Swift consumer of the metadata methods.
//

#import "AirwindowsBridge.h"
#include "../Airwin/AirwinRegistry.h"
#include <memory>
#include <atomic>

// MARK: - AirwindowsEffectInfo

@interface AirwindowsEffectInfo ()
@property (nonatomic, readwrite) NSString *name;
@property (nonatomic, readwrite) NSString *category;
@property (nonatomic, readwrite) NSString *whatText;
@property (nonatomic, readwrite) NSInteger nParams;
@property (nonatomic, readwrite) BOOL isMono;
@property (nonatomic, readwrite) NSInteger registryIndex;
@property (nonatomic, readwrite) NSInteger catChrisOrdering;
@property (nonatomic, readwrite) NSString *firstCommitDate;
@property (nonatomic, readwrite) NSArray<NSString *> *collections;
@property (nonatomic, readwrite, nullable) NSString *postURL;
@property (nonatomic, readwrite, nullable) NSString *videoURL;
@end

@implementation AirwindowsEffectInfo
@end

// Link index: effect name -> { "post": url, "video": url }. Loaded once from
// effect_links.json bundled into the AirwindowsDSP framework.
static NSDictionary<NSString *, NSDictionary *> *sLinkIndex = nil;

// Category overrides: effect name -> overridden category. Lets us correct
// "Unclassified" entries from the upstream registry without editing
// ModuleAdd.h (which is regenerated by airwin2rack on every upstream sync).
// Entries with a leading underscore (e.g. "_comment") are ignored.
static NSDictionary<NSString *, NSString *> *sCategoryOverrides = nil;

// Cached category list and effect-name-by-category map, computed once after
// applying overrides. Recomputed from scratch in case overrides remap
// effects across categories or empty out the "Unclassified" bucket.
static NSArray<NSString *> *sCachedCategories = nil;
static NSDictionary<NSString *, NSArray<NSString *> *> *sCachedFxByCategory = nil;

static NSDictionary<NSString *, NSDictionary *> *AirwindowsLoadLinkIndex(void) {
    if (sLinkIndex) return sLinkIndex;
    NSBundle *bundle = [NSBundle bundleForClass:[AirwindowsEffectInfo class]];
    NSURL *url = [bundle URLForResource:@"effect_links" withExtension:@"json"];
    if (!url) { sLinkIndex = @{}; return sLinkIndex; }
    NSData *data = [NSData dataWithContentsOfURL:url];
    if (!data) { sLinkIndex = @{}; return sLinkIndex; }
    id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
    sLinkIndex = [parsed isKindOfClass:[NSDictionary class]] ? parsed : @{};
    return sLinkIndex;
}

static NSDictionary<NSString *, NSString *> *AirwindowsLoadCategoryOverrides(void) {
    if (sCategoryOverrides) return sCategoryOverrides;
    NSBundle *bundle = [NSBundle bundleForClass:[AirwindowsEffectInfo class]];
    NSURL *url = [bundle URLForResource:@"category_overrides" withExtension:@"json"];
    if (!url) { sCategoryOverrides = @{}; return sCategoryOverrides; }
    NSData *data = [NSData dataWithContentsOfURL:url];
    if (!data) { sCategoryOverrides = @{}; return sCategoryOverrides; }
    id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
    if (![parsed isKindOfClass:[NSDictionary class]]) { sCategoryOverrides = @{}; return sCategoryOverrides; }

    // Filter out underscore-prefixed metadata keys (_comment etc.) and any
    // non-string values. Keeps the JSON file friendly to humans without
    // polluting the runtime map.
    NSMutableDictionary *clean = [NSMutableDictionary dictionary];
    for (id key in parsed) {
        if (![key isKindOfClass:[NSString class]]) continue;
        if ([(NSString *)key hasPrefix:@"_"]) continue;
        id value = parsed[key];
        if (![value isKindOfClass:[NSString class]]) continue;
        if ([(NSString *)value length] == 0) continue;
        clean[key] = value;
    }
    sCategoryOverrides = clean;
    return sCategoryOverrides;
}

/// Returns the effective category for an effect — the override if one exists,
/// otherwise the registry-supplied default.
static NSString *AirwindowsCategoryFor(NSString *effectName, NSString *registryCategory) {
    NSString *override = AirwindowsLoadCategoryOverrides()[effectName];
    return override.length > 0 ? override : registryCategory;
}

static void AirwindowsApplyLinks(AirwindowsEffectInfo *info) {
    NSDictionary *index = AirwindowsLoadLinkIndex();
    NSDictionary *entry = index[info.name];
    if (![entry isKindOfClass:[NSDictionary class]]) return;
    id post = entry[@"post"];
    id video = entry[@"video"];
    if ([post isKindOfClass:[NSString class]]) info.postURL = post;
    if ([video isKindOfClass:[NSString class]]) info.videoURL = video;
}

/// Walks the C++ registry once and builds an overridden categories list +
/// effect-by-category map. Empty categories (e.g. "Unclassified" if every
/// member was reassigned) are dropped. Categories are sorted A–Z — this is
/// the canonical order the UI uses for the browser sidebar and the
/// "by category" grouped list (pinned pseudo-categories like Favorites/New/
/// "All categories" are a UI concern and sit above this list).
static void AirwindowsBuildCategoryCachesIfNeeded(void) {
    if (sCachedCategories && sCachedFxByCategory) return;
    NSMutableOrderedSet<NSString *> *cats = [NSMutableOrderedSet orderedSet];
    NSMutableDictionary<NSString *, NSMutableArray<NSString *> *> *byCat = [NSMutableDictionary dictionary];
    for (size_t i = 0; i < AirwinRegistry::registry.size(); i++) {
        const auto &r = AirwinRegistry::registry[i];
        NSString *name = [NSString stringWithUTF8String:r.name.c_str()];
        NSString *defaultCat = [NSString stringWithUTF8String:r.category.c_str()];
        NSString *cat = AirwindowsCategoryFor(name, defaultCat);
        if (cat.length == 0) continue;
        [cats addObject:cat];
        NSMutableArray *bucket = byCat[cat];
        if (!bucket) { bucket = [NSMutableArray array]; byCat[cat] = bucket; }
        [bucket addObject:name];
    }
    sCachedCategories = [[cats array] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
    sCachedFxByCategory = byCat;
}

// MARK: - AirwindowsEngine
//
// Two roles on one class:
//   - Class methods (above the @implementation below) are pure registry
//     queries: list effects, list categories, look up by index/name.
//   - Instance methods (the @implementation that follows) are the host-
//     shell preview engine: one processor at a time, simple stereo
//     in/out, no thread juggling. Not used by the AUv3 plugin.

@interface AirwindowsEngine () {
    std::unique_ptr<AirwinConsolidatedBase> _processor;
    NSInteger _currentIndex;
    double _sampleRate;
}
@end

static BOOL sRegistryInitialized = NO;

@implementation AirwindowsEngine

+ (void)initializeRegistry {
    if (!sRegistryInitialized) {
        AirwinConsolidatedBase::defaultSampleRate = 44100.f;
        AirwinRegistry::completeRegistry();
        sRegistryInitialized = YES;
    }
}

+ (NSArray<AirwindowsEffectInfo *> *)allEffects {
    [self initializeRegistry];
    NSMutableArray *result = [NSMutableArray arrayWithCapacity:AirwinRegistry::registry.size()];
    for (size_t i = 0; i < AirwinRegistry::registry.size(); i++) {
        const auto &r = AirwinRegistry::registry[i];
        AirwindowsEffectInfo *info = [[AirwindowsEffectInfo alloc] init];
        info.name = [NSString stringWithUTF8String:r.name.c_str()];
        info.category = AirwindowsCategoryFor(
            info.name,
            [NSString stringWithUTF8String:r.category.c_str()]
        );
        info.whatText = [NSString stringWithUTF8String:r.whatText.c_str()];
        info.nParams = r.nParams;
        info.isMono = r.isMono;
        info.registryIndex = (NSInteger)i;
        info.catChrisOrdering = r.catChrisOrdering;
        info.firstCommitDate = [NSString stringWithUTF8String:r.firstCommitDate.c_str()];

        NSMutableArray *cols = [NSMutableArray array];
        for (const auto &c : r.collections) {
            [cols addObject:[NSString stringWithUTF8String:c.c_str()]];
        }
        info.collections = cols;
        AirwindowsApplyLinks(info);

        [result addObject:info];
    }
    return result;
}

+ (NSString *)effectiveCategoryForEffectName:(NSString *)name
                              defaultCategory:(NSString *)defaultCategory {
    return AirwindowsCategoryFor(name, defaultCategory);
}

+ (NSArray<NSString *> *)allCategories {
    [self initializeRegistry];
    AirwindowsBuildCategoryCachesIfNeeded();
    return sCachedCategories;
}

+ (NSArray<NSString *> *)effectNamesInCategory:(NSString *)category {
    [self initializeRegistry];
    AirwindowsBuildCategoryCachesIfNeeded();
    return sCachedFxByCategory[category] ?: @[];
}

+ (NSInteger)effectCount {
    [self initializeRegistry];
    return (NSInteger)AirwinRegistry::registry.size();
}

+ (nullable AirwindowsEffectInfo *)effectInfoAtIndex:(NSInteger)index {
    [self initializeRegistry];
    if (index < 0 || index >= (NSInteger)AirwinRegistry::registry.size()) return nil;
    const auto &r = AirwinRegistry::registry[index];
    AirwindowsEffectInfo *info = [[AirwindowsEffectInfo alloc] init];
    info.name = [NSString stringWithUTF8String:r.name.c_str()];
    info.category = AirwindowsCategoryFor(
        info.name,
        [NSString stringWithUTF8String:r.category.c_str()]
    );
    info.whatText = [NSString stringWithUTF8String:r.whatText.c_str()];
    info.nParams = r.nParams;
    info.isMono = r.isMono;
    info.registryIndex = index;
    info.catChrisOrdering = r.catChrisOrdering;
    info.firstCommitDate = [NSString stringWithUTF8String:r.firstCommitDate.c_str()];
    NSMutableArray *cols = [NSMutableArray array];
    for (const auto &c : r.collections) {
        [cols addObject:[NSString stringWithUTF8String:c.c_str()]];
    }
    info.collections = cols;
    AirwindowsApplyLinks(info);
    return info;
}

+ (NSInteger)indexForEffectName:(NSString *)name {
    [self initializeRegistry];
    std::string n = [name UTF8String];
    auto it = AirwinRegistry::nameToIndex.find(n);
    if (it == AirwinRegistry::nameToIndex.end()) return -1;
    return (NSInteger)it->second;
}

- (instancetype)init {
    self = [super init];
    if (self) {
        [AirwindowsEngine initializeRegistry];
        _currentIndex = -1;
        _sampleRate = 44100.0;
        if (AirwinRegistry::registry.size() > 0) {
            [self selectEffectAtIndex:0];
        }
    }
    return self;
}

- (void)selectEffectAtIndex:(NSInteger)index {
    if (index < 0 || index >= (NSInteger)AirwinRegistry::registry.size()) return;
    _currentIndex = index;
    const auto &reg = AirwinRegistry::registry[index];
    _processor = reg.generator();
    if (_processor) {
        _processor->setSampleRate((float)_sampleRate);
    }
}

- (NSInteger)currentEffectIndex {
    return _currentIndex;
}

- (NSString *)currentEffectName {
    if (_currentIndex < 0) return @"";
    return [NSString stringWithUTF8String:AirwinRegistry::registry[_currentIndex].name.c_str()];
}

- (NSString *)currentEffectCategory {
    if (_currentIndex < 0) return @"";
    return [NSString stringWithUTF8String:AirwinRegistry::registry[_currentIndex].category.c_str()];
}

- (NSInteger)currentParameterCount {
    if (_currentIndex < 0) return 0;
    return (NSInteger)AirwinRegistry::registry[_currentIndex].nParams;
}

- (NSString *)parameterNameAtIndex:(NSInteger)paramIndex {
    if (!_processor || paramIndex < 0) return @"";
    char text[256] = {0};
    _processor->getParameterName((VstInt32)paramIndex, text);
    return [NSString stringWithUTF8String:text];
}

- (NSString *)parameterLabelAtIndex:(NSInteger)paramIndex {
    if (!_processor || paramIndex < 0) return @"";
    char text[256] = {0};
    _processor->getParameterLabel((VstInt32)paramIndex, text);
    return [NSString stringWithUTF8String:text];
}

- (NSString *)parameterDisplayAtIndex:(NSInteger)paramIndex {
    if (!_processor || paramIndex < 0) return @"";
    char text[256] = {0};
    _processor->getParameterDisplay((VstInt32)paramIndex, text);
    return [NSString stringWithUTF8String:text];
}

- (float)parameterValueAtIndex:(NSInteger)paramIndex {
    if (!_processor || paramIndex < 0) return 0.0f;
    return _processor->getParameter((VstInt32)paramIndex);
}

- (void)setParameterValue:(float)value atIndex:(NSInteger)paramIndex {
    if (!_processor || paramIndex < 0) return;
    _processor->setParameter((VstInt32)paramIndex, value);
}

- (void)setSampleRate:(double)sampleRate {
    _sampleRate = sampleRate;
    if (_processor) {
        _processor->setSampleRate((float)sampleRate);
    }
}

- (void)processFloatInputL:(const float *)inL
                    inputR:(const float *)inR
                   outputL:(float *)outL
                   outputR:(float *)outR
                    frames:(int)frames {
    if (!_processor) {
        // Pass through silence
        memset(outL, 0, sizeof(float) * frames);
        memset(outR, 0, sizeof(float) * frames);
        return;
    }

    // Copy input to output buffers (processReplacing works in-place)
    if (inL != outL) memcpy(outL, inL, sizeof(float) * frames);
    if (inR != outR) memcpy(outR, inR, sizeof(float) * frames);

    float *inputs[2] = { outL, outR };
    float *outputs[2] = { outL, outR };

    _processor->processReplacing(inputs, outputs, (VstInt32)frames);
}

@end
